# Example for using the keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  
  push:               # automatically run on changes to following paths
    paths:
      - "config/thermal_pad.keymap"
      - "boards/shields/thermal_pad/xxx.dtsi"
      # - 'boards/*/*/*.keymap'
  
  workflow_dispatch:  # can be triggered manually

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write  # allow workflow to commit to the repo
    with:
      keymap_patterns: "config/thermal_pad.keymap.keymap"        # path to the keymaps to parse
      config_path: "keymap_drawer.config.yaml"  # config file, ignored if not exists
      output_folder: "draw"            # path to save produced SVG and keymap YAML files
      parse_args: ""  # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: ""   # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"
